export {
  SYNTHETIC_DEFAULT_MODEL_ID,
  SYNTHETIC_DEFAULT_MODEL_REF,
} from "../agents/synthetic-models.js";
export { VENICE_DEFAULT_MODEL_ID, VENICE_DEFAULT_MODEL_REF } from "../agents/venice-models.js";
export {
  applyAuthProfileConfig,
  applyCloudflareAiGatewayConfig,
  applyCloudflareAiGatewayProviderConfig,
  applyKimiCodingConfig,
  applyKimiCodingProviderConfig,
  applyMoonshotConfig,
  applyMoonshotCnConfig,
  applyMoonshotProviderConfig,
  applyMoonshotCnProviderConfig,
  applyOpenrouterConfig,
  applyOpenrouterProviderConfig,
  applySyntheticConfig,
  applySyntheticProviderConfig,
  applyVeniceConfig,
  applyVeniceProviderConfig,
  applyVercelAiGatewayConfig,
  applyVercelAiGatewayProviderConfig,
  applyVolcengineConfig,
  applyVolcengineProviderConfig,
  applyXiaomiConfig,
  applyXiaomiProviderConfig,
  applyZaiConfig,
} from "./onboard-auth.config-core.js";
export {
  applyEphoneConfig,
  applyEphoneProviderConfig,
  applySiliconflowConfig,
  applySiliconflowProviderConfig,
  applyDashscopeConfig,
  applyDashscopeProviderConfig,
  applyDashscopeCodingPlanConfig,
  applyDashscopeCodingPlanProviderConfig,
  applyDeepseekConfig,
  applyDeepseekProviderConfig,
  applyMoonshotCodingPlanConfig,
  applyMoonshotCodingPlanProviderConfig,
  applyVolcengineCodingPlanConfig,
  applyVolcengineCodingPlanProviderConfig,
  applyCustomProviderConfig,
} from "./onboard-auth.config-core.js";
export {
  applyMinimaxApiConfig,
  applyMinimaxApiProviderConfig,
  applyMinimaxConfig,
  applyMinimaxHostedConfig,
  applyMinimaxHostedProviderConfig,
  applyMinimaxProviderConfig,
} from "./onboard-auth.config-minimax.js";

export {
  applyOpencodeZenConfig,
  applyOpencodeZenProviderConfig,
} from "./onboard-auth.config-opencode.js";
export {
  CLOUDFLARE_AI_GATEWAY_DEFAULT_MODEL_REF,
  OPENROUTER_DEFAULT_MODEL_REF,
  setAnthropicApiKey,
  setCloudflareAiGatewayConfig,
  setGeminiApiKey,
  setKimiCodingApiKey,
  setMinimaxApiKey,
  setMoonshotApiKey,
  setOpencodeZenApiKey,
  setOpenrouterApiKey,
  setSyntheticApiKey,
  setVeniceApiKey,
  setVercelAiGatewayApiKey,
  setVolcengineApiKey,
  setXiaomiApiKey,
  setZaiApiKey,
  writeOAuthCredentials,
  VERCEL_AI_GATEWAY_DEFAULT_MODEL_REF,
  XIAOMI_DEFAULT_MODEL_REF,
  ZAI_DEFAULT_MODEL_REF,
} from "./onboard-auth.credentials.js";
export {
  setEphoneApiKey,
  setSiliconflowApiKey,
  setDashscopeApiKey,
  setDashscopeCodingPlanApiKey,
  setMoonshotCodingPlanApiKey,
  setVolcengineCodingPlanApiKey,
  setDeepseekApiKey,
} from "./onboard-auth.credentials.js";
export {
  buildMinimaxApiModelDefinition,
  buildMinimaxModelDefinition,
  buildMoonshotModelDefinition,
  DEFAULT_MINIMAX_BASE_URL,
  MOONSHOT_CN_BASE_URL,
  KIMI_CODING_MODEL_ID,
  KIMI_CODING_MODEL_REF,
  MINIMAX_API_BASE_URL,
  MINIMAX_HOSTED_MODEL_ID,
  MINIMAX_HOSTED_MODEL_REF,
  MOONSHOT_BASE_URL,
  MOONSHOT_DEFAULT_MODEL_ID,
  MOONSHOT_DEFAULT_MODEL_REF,
} from "./onboard-auth.models.js";
export {
  EPHONE_BASE_URL,
  EPHONE_DEFAULT_MODEL_REF,
  EPHONE_DEFAULT_MODEL_ID,
  EPHONE_MODELS,
  buildEphoneModelDefinition,
  SILICONFLOW_BASE_URL,
  SILICONFLOW_DEFAULT_MODEL_REF,
  DASHSCOPE_BASE_URL,
  DASHSCOPE_CODING_PLAN_BASE_URL,
  DASHSCOPE_DEFAULT_MODEL_REF,
  DASHSCOPE_CODING_PLAN_DEFAULT_MODEL_REF,
  DASHSCOPE_CODING_PLAN_DEFAULT_MODEL_ID,
  DASHSCOPE_CODING_PLAN_MODELS,
  DEEPSEEK_BASE_URL,
  DEEPSEEK_DEFAULT_MODEL_REF,
  MOONSHOT_CODING_PLAN_BASE_URL,
  MOONSHOT_CODING_PLAN_DEFAULT_MODEL_ID,
  MOONSHOT_CODING_PLAN_DEFAULT_MODEL_REF,
  buildSiliconflowModelDefinition,
  buildDashscopeModelDefinition,
  buildDashscopeCodingPlanModelDefinition,
  buildMoonshotCodingPlanModelDefinition,
  buildVolcengineCodingPlanModelDefinition,
  VOLCENGINE_CODING_PLAN_BASE_URL,
  VOLCENGINE_CODING_PLAN_DEFAULT_MODEL_ID,
  VOLCENGINE_CODING_PLAN_DEFAULT_MODEL_REF,
  buildDeepseekModelDefinition,
} from "./onboard-auth.models.js";

export async function setHuggingfaceApiKey(
  apiKey: string,
  store: Record<string, unknown>,
): Promise<void> {
  store["huggingface.apiKey"] = apiKey;
}
